global:
  resolve_timeout: 5m

route:
  receiver: "null"
  group_by: ['alertname', 'namespace']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - matchers:
    - alertname = "Watchdog"
    receiver: "null"

receivers:
  - name: "teams-notifications"
    webhook_configs:
      - send_resolved: true
        url: "http://prom2teams.default.svc.cluster.local:8089"
  - name: "null"

inhibit_rules:
- source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ "warning|info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
  equal:
  - namespace
  - alertname
- source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
  equal:
  - namespace
- target_matchers:
  - alertname = InfoInhibitor

templates:
  - /etc/alertmanager/config/*.tmpl
