apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom2teams
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom2teams
  template:
    metadata:
      labels:
        app: prom2teams
    spec:
      hostNetwork: true
      containers:
        - name: prom2teams
          image: idealista/prom2teams:latest
          ports:
            - containerPort: 8089
          env:
            - name: PROM2TEAMS_CONNECTOR
              value: "https://outlook.office.com/webhook....."

          readinessProbe:
            httpGet:
              path: /alive
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /ready
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: prom2teams
  namespace: default
spec:
  selector:
    app: prom2teams
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP
